export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const CREATE_COLLECTION = "CREATE_COLLECTION";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";

export const DELETE_COLLECTION_OPTIMISTIC = "DELETE_COLLECTION_OPTIMISTIC";

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';